### ISSUE TITLE
Potential Page Speed Optimizations

### ISSUE THREAD

**Issue by LeeBergstrand** [trucsclub/trucsclub.github.io#80]
@LavenderGoons 

Google has some page speed optimized insights.
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.trucsclub.ca%2F

Most of this stuff is outside you control but may be worth looking into...

**Comment by chrisfosterelli** [comment]
Most of these are caused by things that are not directly under our control: the twitter plugin, Github's HTTP server, Facebook's JS, etc.. As you pointed out.

An argument could be made for moving the JS to the bottom of the DOM or making them async. I wouldn't bother with the CSS inlining, as that's a ton of work and difficult to fit into a github pages workflow.

@LeeBergstrand Pull requests welcome!

**Comment by stevelyall** [comment]
@LeeBergstrand  #overoptimization :P

**Comment by LeeBergstrand** [comment]
@stevelyall 

![](https://i.ytimg.com/vi/paZcBwCLLBM/maxresdefault.jpg)

@chrisfosterelli --> Overall its good! I'll look into the ayncing the JS after exams.

**Comment by marcolussetti** [comment]
Closing as stale. We could probably do with a rewrite anyway.
