### ISSUE TITLE
Implement use of constants in css

### ISSUE THREAD

**Issue by cryptonym0** [trucsclub/trucsclub.github.io#83]
Constants = Good Practice 

_Acceptance Criteria_
1. Create constants css folder including main site properties (i.e. common sizes, colours.ect)
2. Implement use of constants in css code

**Comment by chrisfosterelli** [comment]
I think you could also make an argument for why you might not want to do this, since it would require that you add a CSS preprocessor to the project (SASS/Less/etc) which would then also include a build step and compiler.

If the goal is to encourage participation with the website, then this greatly increases the barrier for a newbie getting involved because it requires much more than HTML/CSS knowledge. The benefit on a smaller site may not be worth the tradeoff.

I'm not a web admin though, just food for thought since I still subscribe here :)

**Comment by mitchhentges** [comment]
@LavenderGoons I'd recommend not having any `constants`, because dealing with a "compiled" stylesheet language, like SASS or LESS, is not necessary for such a small project.
